### ISSUE TITLE
{cmd/,}imports: add whitelisting

### ISSUE THREAD

**Issue by kortschak** [gonum/tools#4]
I am involved in a project that has a tight import budget due to the the hardware that the code runs on. It would be useful in that project to be able to have import whitelisting in addition to blacklisting.

Addition of whitelisting adds some semantic complexity that needs to be discussed dealing with the order of list application. ISTM that the most sensible order is to whitelist first and then apply the blacklist to that, carving out items in the whitelist that are not wanted. In the case that the whitelist is empty, then everything is initially whitelisted. In the case that the blacklist is empty then only items in the (non-empty) whitelist are accepted. If both are empty, it is a no-op.

After the API is settled, I'll do the work for this.

**Comment by sbinet** [comment]
yes, speaking of past experience, whitelist and then blacklist is the most sensible and palatable option.

SGTM.

**Comment by btracey** [comment]
SGTM
